version: '3'

services:
 nginx:
  build: ./nginx
  ports:
   - 80:80
  volumes:
   - ./code:/www:z
  networks:
   - nginx-php
 
 myphp:
  build: ./php
  container_name: myphp
  volumes:
   - ./code:/www:z
  networks:
   - nginx-php

networks:
  nginx-php: