version: '3'

services:
 nginx:
  build: ./nginx
  ports:
   - 80:80
  volumes:
   - ./code:/www:z
  working_dir: /www  
  links:
   - myphp
 
 myphp:
  build: ./php
  container_name: myphp
  volumes:
   - ./code:/www:z
  working_dir: /www
