---
# tasks file for deploy_nginx

- block: ########## CentOS #########

  - name: Add Nginx Repository for CentOS
    yum_repository:
      name: nginx
      description: NGINX
      file: nginx
      baseurl: https://nginx.org/packages/mainline/centos/$releasever/$basearch/
      gpgcheck: false
      enabled: true


  - name: Nginx Install to CentOS
    yum:
      name: nginx     
      state: present
    notify:
      - restart nginx
  when: ansible_os_family == "RedHat"

- block: ########## Ubuntu #########
    - name: Add key for Repository
      apt_key:
        url: http://nginx.org/keys/nginx_signing.key
        state: present

    - name: Install Nginx Repo Ubuntu
      apt_repository:
        repo: deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx
        state: present
        filename: nginx.list
        update_cache: true
      
    - name: Update apt 
      apt:
        update_cache: true 

    - name: Nginx Install to Ubuntu
      apt:
        name: nginx     
        state: present
        update_cache: true
      notify:
      - restart nginx
  when: ansible_os_family == "Debian"  


############### Template #################

- name: Nginx config file from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
