---
- name: Install OpenVPN Client
  hosts: ovpn-client
  become: true

  tasks:

    - name: 'Install epel-release'
      yum:
        name: epel-release
        state: present
    
    - name: Install Packages
      yum:
        name: 
          - openvpn
          - iperf3
        state: present

    - name: 'Copy Certificates'
      copy:
        src: keys/{{ item }}
        dest: /etc/openvpn/client/
        mode: 0600
      with_items:
        ['ca.crt','ta.key','vpn-client.crt','vpn-client.key'] 

    - name: 'Copy OpenVPN configs files'
      copy:
        src: conf/client.conf
        dest: /etc/openvpn/client/
      
    - name: Create a symbolic link
      file:
        src: /etc/openvpn/client/client.conf
        dest: /etc/openvpn/client.conf
        state: link
      notify:
        - restart openvpn client  

  handlers: 

    - name: restart openvpn client
      systemd:
        name: openvpn@client
        state: restarted
        enabled: yes  