# Describe VMs
MACHINES = {
  # VM name "kernel update"
  :"CentOS-8" => {
              # VM box
              :box_name => "centos/8",
              # VM CPU count
              :cpus => 2,
              # VM RAM size (Mb)
              :memory => 2048
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Disable shared folders
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Apply VM config
    config.vm.define boxname do |box|
      # Set VM base box and hostname
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
	
      # VM resources config
      box.vm.provider "virtualbox" do |v|
        # Set VM RAM size and CPU count
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]

		end
   end
   end
end
