---
- name: lesson 37
  hosts: web
  become: true

  tasks:

    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive
        

    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Packege Install
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - python-django   
        - go      

### Nginx PHP-FPM ###
    
    - name: 'Install PHP-FPM'
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        # - php-mbstring
        # - php-mysql
        # - php-xml
        # - php-simplexml

    - name: 'Change php-fpm to listen on socket'
      ini_file: dest=/etc/php-fpm.d/www.conf
        section=www
        option=listen
        value=127.0.0.1:9000             


    - name: 'php-fpm listen mode should always be 0660'
      ini_file: dest=/etc/php-fpm.d/www.conf
        section=www
        option=listen.mode
        value=0660     

    - name: 'Change php-fpm user'
      ini_file: dest=/etc/php-fpm.d/www.conf
        section=www
        option=user
        value=nginx

    - name: 'Change php-fpm group'
      ini_file: dest=/etc/php-fpm.d/www.conf
        section=www
        option=group
        value=nginx

    - name: 'Change php-fpm listen.owner'
      ini_file: dest=/etc/php-fpm.d/www.conf
        section=www
        option=listen.owner
        value=nginx

    - name: 'Change php-fpm listen.group'
      ini_file: dest=/etc/php-fpm.d/www.conf
        section=www
        option=listen.group
        value=nginx
              
### Django ###      


    - name: Install a django project
      command: django-admin startproject django_project

    - name: generate database django project
      command: python /home/vagrant/django_project/manage.py migrate

    # - django_manage:
    #     command: migrate
    #     app_path: django_project/manage.py

    - name: Config Django settings.py
      lineinfile: 
        dest: /home/vagrant/django_project/django_project/settings.py
        regexp: "{{ item.regexp }}" 
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: "^ALLOWED_HOSTS", line: "ALLOWED_HOSTS = ['127.0.0.1']" }        

######
    - name: copy config
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}" 
      with_items:
        - { src: 'files/django.service', dest: '/etc/systemd/system/', mode: '0644' }
        - { src: 'files/go.service', dest: '/etc/systemd/system/', mode: '0644' }
        - { src: 'files/nginx/nginx.conf', dest: '/etc/nginx/', mode: '0644' }
        - { src: 'files/nginx/go.conf', dest: '/etc/nginx/conf.d/', mode: '0644' }
        - { src: 'files/nginx/wordpress.conf', dest: '/etc/nginx/conf.d/', mode: '0644' }
        - { src: 'files/nginx/django.conf', dest: '/etc/nginx/conf.d/', mode: '0644' }
        - { src: 'files/nginx/hello', dest: '/home/vagrant/go/', mode: '0755' }
        - { src: 'files/nginx/wordpress.php', dest: '/usr/share/nginx/html/index.php', mode: '0664' }
      notify:
        - restart services   

  handlers:

  - name: restart services
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - django
      - nginx  
      - go 
      - php-fpm   
