Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
  web.vm.box = "centos/7"
  web.vm.network "private_network", ip: "192.168.50.10"
  web.vm.hostname = "web"
  web.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  web.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
    SHELL
  web.vm.provision  "shell", path: "scripts/web.sh"
  end

  config.vm.define "log" do |log|
  log.vm.box = "centos/7"
  log.vm.network "private_network", ip: "192.168.50.20"
  log.vm.hostname = "log"
  log.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  log.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
    SHELL
  log.vm.provision  "shell", path: "scripts/log.sh" 
  end


  config.vm.define "elk" do |elk|
  elk.vm.box = "centos/7"
  elk.vm.network "private_network", ip: "192.168.50.30"
  elk.vm.hostname = "elk"
  elk.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  elk.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
    SHELL
  elk.vm.provision  "shell", path: "scripts/elk.sh" 
  end

end